/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package updatequestions;
import questionsdb.QuestionsDB;

/**
 *
 * @author Bibek
 */
import javax.swing.*;
import static updatequestions.EditQuestionDialog.questionNum;

public class AddQuestionDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddQuestionDialog
     */
    private static String questionNum;
    private static String subject;
    public static void setQuestionNum(String qn)
    {
        questionNum=qn;
    }
     public static void setSubject(String s)
    {
        subject=s;
    }
    public AddQuestionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon i=new ImageIcon(getClass().getResource("/images/projecticon.png"));
        setIconImage(i.getImage());
        initWeightage();
    }
    public void initWeightage()
    {
       DefaultComboBoxModel model = new DefaultComboBoxModel();
       if(model.getSize()!=0)
       {
            model.removeAllElements();
       }
       if(questionNum.equals("7a") || questionNum.equals("7b") || questionNum.equals("7c"))
       {
           model.addElement("5");
       }
       else
       {
          model.addElement("7");
          model.addElement("8");
       }
       weight.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        enteredq = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        weight = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(220, 40, 0, 0));
        setMinimumSize(new java.awt.Dimension(430, 250));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Question:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 73, 22);

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(322, 39, 79, 23);

        cancel.setText("cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(322, 86, 79, 23);

        enteredq.setColumns(20);
        enteredq.setRows(5);
        jScrollPane1.setViewportView(enteredq);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 39, 294, 169);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Weightage");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 10, 90, 20);

        weight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "7", "8" }));
        getContentPane().add(weight);
        weight.setBounds(216, 10, 90, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background4.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 450, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        if(enteredq.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Enter a question first" );
            return;
        }
        if(weight.getSelectedItem().toString().equals("none"))
        {
            JOptionPane.showMessageDialog(this,"Select the weightage" );
            return;
        }
        QuestionsDB qd=new QuestionsDB(subject,questionNum);
        qd.addQuestion(subject,questionNum,enteredq.getText(),weight.getSelectedItem().toString());
        
        
        dispose();
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton cancel;
    private javax.swing.JTextArea enteredq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> weight;
    // End of variables declaration//GEN-END:variables
}
