/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package updatequestions;

import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import questionsdb.QuestionsDB;

/**
 *
 * @author Bibek
 */
public class EditQuestionDialog extends javax.swing.JDialog {

    static String questionNum;
    static String subject;
    public static void setQuestionNum(String qn)
    {
        questionNum=qn;
    }
    public static void setSubject(String s)
    {
        subject=s;
    }
    /**
     * Creates new form EditQuestionDialog
     */
    public EditQuestionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon i=new ImageIcon(getClass().getResource("/images/projecticon.png"));
        setIconImage(i.getImage());
        initWeightage();
    }
    public void initWeightage()
    {
       DefaultComboBoxModel model = new DefaultComboBoxModel();
       if(model.getSize()!=0)
       {
            model.removeAllElements();
       }
       if(questionNum.equals("7a") || questionNum.equals("7b") || questionNum.equals("7c"))
       {
           model.addElement("5");
       }
       else
       {
          model.addElement("7");
          model.addElement("8");
       }
       weight.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enteredID = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        enteredQ = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        weight = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(220, 40, 0, 0));
        setMinimumSize(new java.awt.Dimension(480, 350));
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Question's ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(26, 21, 103, 22);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Question:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 90, 103, 14);

        enteredID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteredIDActionPerformed(evt);
            }
        });
        getContentPane().add(enteredID);
        enteredID.setBounds(133, 22, 220, 30);

        cancel.setText("cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(270, 270, 77, 23);

        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(130, 270, 74, 23);

        enteredQ.setColumns(20);
        enteredQ.setRows(5);
        jScrollPane1.setViewportView(enteredQ);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 90, 294, 169);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Weightage");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 60, 90, 20);

        weight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        getContentPane().add(weight);
        weight.setBounds(130, 60, 100, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background4.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 460, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
         QuestionsDB qd=new QuestionsDB(subject,questionNum);
        if(qd.checkID(enteredID.getText())==false)
        {
            JOptionPane.showMessageDialog(this,"Enter a valid question's id first" );
            return;
        }
        if(enteredQ.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Enter a valid question first" );
            return;
        }
        
        qd.editQuestion(subject,enteredID.getText(),enteredQ.getText(),weight.getSelectedItem().toString());
        
        
        dispose();
    }//GEN-LAST:event_saveActionPerformed

    private void enteredIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteredIDActionPerformed
        // TODO add your handling code here:
        
        QuestionsDB q=new QuestionsDB(subject,questionNum);
        enteredQ.setText(q.getQuestionByID(enteredID.getText()));
        weight.setSelectedItem(q.getWeightage(enteredID.getText()));
    }//GEN-LAST:event_enteredIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditQuestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditQuestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditQuestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditQuestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditQuestionDialog dialog = new EditQuestionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField enteredID;
    private javax.swing.JTextArea enteredQ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> weight;
    // End of variables declaration//GEN-END:variables
}
