/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package updatequestions;

import questionsdb.QuestionsDB;
import questionsdb.Question;
import javax.swing.*;
import questionsdb.SubjectDB;
/**
 *
 * @author Bibek
 */
public class UpdateQuestion extends javax.swing.JFrame {

    /**
     * Creates new form UpdateQuestion
     */
    private  Question questions[];
    
    private String subjects[];
   
    
    public UpdateQuestion() {
        super("Questions Generator- Update Question");
        initComponents();
        ImageIcon i=new ImageIcon(getClass().getResource("/images/projecticon.png"));
        setIconImage(i.getImage());
        initSubjects();
    }
    private void initSubjects()
    {
        SubjectDB s=new SubjectDB();
        subjects=s.getSubjects();
        for(int i=0;i<subjects.length;i++)
        {
            selectedSubject.addItem(subjects[i]);
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addQuestion = new javax.swing.JButton();
        editQuestion = new javax.swing.JButton();
        questionNum = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionsArea = new javax.swing.JTextArea();
        deleteQuestion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        selectedSubject = new javax.swing.JComboBox<>();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(220, 40, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        addQuestion.setText("Add question");
        addQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuestionActionPerformed(evt);
            }
        });
        getContentPane().add(addQuestion);
        addQuestion.setBounds(650, 100, 120, 23);

        editQuestion.setText("Edit Question");
        editQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editQuestionActionPerformed(evt);
            }
        });
        getContentPane().add(editQuestion);
        editQuestion.setBounds(650, 140, 120, 23);

        questionNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "1a", "1b", "2a", "2b", "3a", "3b", "4a", "4b", "5a", "5b", "6a", "6b", "7a", "7b", "7c" }));
        questionNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionNumActionPerformed(evt);
            }
        });
        getContentPane().add(questionNum);
        questionNum.setBounds(330, 70, 64, 20);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Question Num");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 70, 82, 14);

        questionsArea.setEditable(false);
        questionsArea.setColumns(20);
        questionsArea.setRows(5);
        jScrollPane1.setViewportView(questionsArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 100, 550, 420);

        deleteQuestion.setText("Delete Question");
        deleteQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteQuestionActionPerformed(evt);
            }
        });
        getContentPane().add(deleteQuestion);
        deleteQuestion.setBounds(650, 180, 120, 23);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Subject");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 70, 61, 14);

        selectedSubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));
        selectedSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedSubjectActionPerformed(evt);
            }
        });
        getContentPane().add(selectedSubject);
        selectedSubject.setBounds(130, 70, 71, 20);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(650, 220, 120, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background4.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 810, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editQuestionActionPerformed
        // TODO add your handling code here:
        if(selectedSubject.getSelectedItem().toString().equals("none"))
            {
                JOptionPane.showMessageDialog(this,"Select subject first" );
                return;
            }

        if(questionNum.getSelectedItem().toString().equals("none"))
            {
                JOptionPane.showMessageDialog(this,"Select a question num" );
                return;
            }
                 
       EditQuestionDialog.setQuestionNum(questionNum.getSelectedItem().toString());
       EditQuestionDialog.setSubject(selectedSubject.getSelectedItem().toString());
       EditQuestionDialog d=new EditQuestionDialog(this,true);
       d.setTitle("Questions Generator-edit question");
      
       d.setVisible(true); 
       questionNum.setSelectedItem(questionNum.getSelectedItem());
    }//GEN-LAST:event_editQuestionActionPerformed

    private void questionNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionNumActionPerformed
        // TODO add your handling code here:
        questionsArea.setText("");
        try
        {
           
            if(selectedSubject.getSelectedItem().toString().equals("none"))
            {
                //JOptionPane.showMessageDialog(this,"Select subject first" );
                questionNum.setSelectedItem("none");
                return;
            }
            if(questionNum.getSelectedItem().toString().equals("none"))
            {
                questionsArea.setText("");
                return;

            }
            QuestionsDB q=new QuestionsDB(selectedSubject.getSelectedItem().toString(),questionNum.getSelectedItem().toString());
            questions=q.getQuestions();
            for(int i=0;i<questions.length;i++)
            {
                
                String temp=questionsArea.getText()+"ID:-"+questions[i].id+"  "+questions[i].question+"\t("+questions[i].weightage+")\n\n";
                
                questionsArea.setText(temp);
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_questionNumActionPerformed

    private void addQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuestionActionPerformed
        // TODO add your handling code here:
        if(selectedSubject.getSelectedItem().toString().equals("none"))
            {
                JOptionPane.showMessageDialog(this,"Select subject first" );
                return;
            }

        if(questionNum.getSelectedItem().toString().equals("none"))
            {
                JOptionPane.showMessageDialog(this,"Select a question num" );
                return;
            }
       AddQuestionDialog.setSubject(selectedSubject.getSelectedItem().toString());
       AddQuestionDialog.setQuestionNum(questionNum.getSelectedItem().toString());
       AddQuestionDialog d=new AddQuestionDialog(this,true);
       d.setTitle("Questions Generator-add question");
       d.setVisible(true);
       questionNum.setSelectedItem(questionNum.getSelectedItem());
    }//GEN-LAST:event_addQuestionActionPerformed

    private void deleteQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteQuestionActionPerformed
        if(selectedSubject.getSelectedItem().toString().equals("none"))
            {
                JOptionPane.showMessageDialog(this,"Select subject first" );
                return;
            }

        if(questionNum.getSelectedItem().toString().equals("none"))
            {
                JOptionPane.showMessageDialog(this,"Select a question num" );
                return;
            }
        
       DeleteQuestionDialog d=new DeleteQuestionDialog(this,true);
       d.setTitle("Questions Generator-delete question");
       d.setQuestionNum(questionNum.getSelectedItem().toString());
       d.setSubject(selectedSubject.getSelectedItem().toString());
       d.setVisible(true);        // TODO add your handling code here:
       questionNum.setSelectedItem(questionNum.getSelectedItem());
    }//GEN-LAST:event_deleteQuestionActionPerformed

    private void selectedSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedSubjectActionPerformed
        // TODO add your handling code here:
            questionsArea.setText("");
            questionNum.setSelectedItem("none");
        
    }//GEN-LAST:event_selectedSubjectActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        admin.AdminOptions.main(new String[]{});
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addQuestion;
    private javax.swing.JButton back;
    private javax.swing.JButton deleteQuestion;
    private javax.swing.JButton editQuestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> questionNum;
    private javax.swing.JTextArea questionsArea;
    private javax.swing.JComboBox<String> selectedSubject;
    // End of variables declaration//GEN-END:variables
}
