
package manageusers;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import questionsdb.UsersDB;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bibek
 */
public class ManageUsers extends javax.swing.JFrame {

    /**
     * Creates new form ManageUsers
     */
    private String userName[];
    public ManageUsers() {
        initComponents();
        ImageIcon i=new ImageIcon(getClass().getResource("/images/projecticon.png"));
        setIconImage(i.getImage());
        refreshList();
    }
    public void refreshList()
    {   
        DefaultListModel dm;
        dm=new DefaultListModel();
        UsersDB sd=new UsersDB();
        userName=sd.getUsers();
        for(int i=0;i<userName.length;i++)
        {
            dm.addElement(userName[i]);
        }
        usersList.setModel(dm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersList = new javax.swing.JList<>();
        addUsers = new javax.swing.JButton();
        deleteUsers = new javax.swing.JButton();
        back = new javax.swing.JButton();
        changePassword = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(220, 40, 0, 0));
        setMinimumSize(new java.awt.Dimension(700, 560));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Users:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 4, 70, 30);

        jScrollPane1.setViewportView(usersList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 44, 450, 450);

        addUsers.setText("Add User");
        addUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUsersActionPerformed(evt);
            }
        });
        getContentPane().add(addUsers);
        addUsers.setBounds(500, 50, 140, 23);

        deleteUsers.setText("Delete User");
        deleteUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUsersActionPerformed(evt);
            }
        });
        getContentPane().add(deleteUsers);
        deleteUsers.setBounds(500, 90, 140, 23);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(500, 170, 140, 23);

        changePassword.setText("Change Password");
        changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(changePassword);
        changePassword.setBounds(500, 130, 140, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background4.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUsersActionPerformed
        // TODO add your handling code here:
        AddUser u=new AddUser(this,true);
        u.setTitle("QuestionsGenerator-add User");
        u.setVisible(true);
        refreshList();
    }//GEN-LAST:event_addUsersActionPerformed

    private void deleteUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUsersActionPerformed
        // TODO add your handling code here:
        if(usersList.isSelectionEmpty())
        {
            JOptionPane.showMessageDialog(this,"Select a user to remove" );
            return;
        }
        DeleteUser d=new DeleteUser(this,true);
        d.setTitle("QuestionsGenerator-remove User");
        d.setName(usersList.getSelectedValue());
        d.setVisible(true);
        refreshList();
        
    }//GEN-LAST:event_deleteUsersActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        admin.AdminOptions.main(new String[]{});
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordActionPerformed
        // TODO add your handling code here:
        if(usersList.isSelectionEmpty())
        {
            JOptionPane.showMessageDialog(this,"Select a user to change password" );
            return;
        }
        ChangePassword d=new ChangePassword(this,true);
        d.setTitle("QuestionsGenerator-change user's password");
        d.setName(usersList.getSelectedValue());
        d.setVisible(true);
        refreshList();
    }//GEN-LAST:event_changePasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUsers;
    private javax.swing.JButton back;
    private javax.swing.JButton changePassword;
    private javax.swing.JButton deleteUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> usersList;
    // End of variables declaration//GEN-END:variables
}
