
package login;

import javax.swing.*;
import useroptions.*;
import questionsdb.UsersDB;
public class UserLogin extends javax.swing.JFrame {

    
    
    public UserLogin() {
        super("Questions Generator-Users Login");
        initComponents();
        ImageIcon i=new ImageIcon(getClass().getResource("/images/projecticon.png"));
        setIconImage(i.getImage());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p = new javax.swing.JPanel();
        userlabel = new javax.swing.JLabel();
        passwordlabel = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        loginimg = new javax.swing.JLabel();
        signin = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(220, 40, 0, 0));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(750, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        p.setBackground(new java.awt.Color(102, 153, 255));
        p.setMaximumSize(new java.awt.Dimension(565, 312));
        p.setLayout(null);

        userlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userlabel.setForeground(new java.awt.Color(255, 255, 255));
        userlabel.setText("UserName");
        p.add(userlabel);
        userlabel.setBounds(380, 180, 107, 26);

        passwordlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordlabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordlabel.setText("Password");
        p.add(passwordlabel);
        passwordlabel.setBounds(380, 240, 112, 26);
        p.add(username);
        username.setBounds(490, 180, 150, 30);

        loginimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user1.png"))); // NOI18N
        p.add(loginimg);
        loginimg.setBounds(70, 150, 240, 250);

        signin.setText("Sign In");
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });
        p.add(signin);
        signin.setBounds(530, 310, 112, 28);
        p.add(password);
        password.setBounds(490, 240, 150, 30);

        cancel.setText("cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        p.add(cancel);
        cancel.setBounds(390, 310, 116, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background4.jpg"))); // NOI18N
        p.add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 590);

        getContentPane().add(p);
        p.setBounds(0, 0, 790, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
        UsersDB p=new UsersDB();
        if(p.validateLogin(username.getText(),password.getText()))
        {
           
            UserOptions.main(new String[]{});
            dispose();
        }
        else
        {
            username.setText("");
            password.setText("");
            JOptionPane.showMessageDialog(this,"Username or password donot match" );
        }           
    }//GEN-LAST:event_signinActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        questionsgenerator.QuestionsGenerator.main(new String[]{});
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
     
     }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel loginimg;
    private javax.swing.JPanel p;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JButton signin;
    private javax.swing.JLabel userlabel;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
