/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package useroptions;


import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import pdfconvert.PDFConvert;
import questionsdb.GeneratedDB;
import questionsdb.Question;
import questionsdb.SubjectDB;
/**
 *
 * @author Bibek
 */

public class GenerateQuestion extends javax.swing.JFrame {

    /**
     * Creates new form GenerateQuestion
     */
    private String subjects[];
   
    private Question questions[];
    public GenerateQuestion() {
        super("QuestionsGenerator- Generate Questions");
        initComponents();
        ImageIcon i=new ImageIcon(getClass().getResource("/images/projecticon.png"));
        setIconImage(i.getImage());
        
        initSubjects();
    }
    private void initSubjects()
    {
        SubjectDB s=new SubjectDB();
        subjects=s.getSubjects();
        for(int i=0;i<subjects.length;i++)
        {
            selectedSubject.addItem(subjects[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selectedSubject = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionPaper = new javax.swing.JTextArea();
        generate = new javax.swing.JButton();
        back = new javax.swing.JButton();
        export = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(220, 40, 0, 0));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Subject:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 30, 57, 14);

        selectedSubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));
        selectedSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedSubjectActionPerformed(evt);
            }
        });
        getContentPane().add(selectedSubject);
        selectedSubject.setBounds(180, 30, 73, 20);

        questionPaper.setEditable(false);
        questionPaper.setColumns(20);
        questionPaper.setRows(5);
        jScrollPane1.setViewportView(questionPaper);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 70, 650, 490);

        generate.setText("Generate Questions");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });
        getContentPane().add(generate);
        generate.setBounds(300, 30, 175, 23);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(700, 130, 80, 23);

        export.setText("Export");
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });
        getContentPane().add(export);
        export.setBounds(700, 90, 80, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background4.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        
        UserOptions.main(new String[]{});
        
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        // TODO add your handling code here:
         String temp;
        if(selectedSubject.getSelectedItem().toString().equals("none"))
        {
            questionPaper.setText("");
            JOptionPane.showMessageDialog(this,"Select subject first" );
            return;
        }
        
        
        makeQuestions();
    }//GEN-LAST:event_generateActionPerformed

    private void selectedSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedSubjectActionPerformed
        // TODO add your handling code here:
        questionPaper.setText("");
            
    }//GEN-LAST:event_selectedSubjectActionPerformed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        // TODO add your handling code here:
        if(questionPaper.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Questions not ready");
            return;
        }
       
        PDFConvert p = new PDFConvert(questionPaper.getText());
    }//GEN-LAST:event_exportActionPerformed
     private void makeQuestions()
     {
        GeneratedDB g=new GeneratedDB(selectedSubject.getSelectedItem().toString());
         String temp="";
         try
         {
             questions = g.getQuestionPaper();
             temp= "                       Gandaki College of Engineering and Science\n";
             temp+="                                  Lamachaur,Pokhara-16\n";
             temp+="Level: Bachelor                                                              FM:100\n";
             temp+="Programme:BE                                                              PM:45\n";
             temp+="Course: "+selectedSubject.getSelectedItem().toString()+"\n\n\n";
            for(int i=0;i<questions.length;i++)
            {
                temp+=questions[i].questionNum+")  "+questions[i].question+"\t("+questions[i].weightage+")\n\n";
                if(questions[i].questionNum.equals("6b"))
                {
                    temp+="Write Short notes on any two:\n\n";
                }
            }
            questionPaper.setText(temp); 
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(this,"Cant generate!! not sufficient data" );
         }
     }/** 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateQuestion().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton export;
    private javax.swing.JButton generate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea questionPaper;
    private javax.swing.JComboBox<String> selectedSubject;
    // End of variables declaration//GEN-END:variables
}
