/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;


import updatequestions.UpdateQuestion;
import admin.admindetails.ChangePassword;
import javax.swing.ImageIcon;
import manageusers.ManageUsers;


/**
 *
 * @author Bibek
 */
public class AdminOptions extends javax.swing.JFrame {

    /**
     * Creates new form AdminOptions
     */
    private static String currentUser;
    
    public AdminOptions() {
        super("Questions Generator-Admin");
        initComponents();
        ImageIcon i=new ImageIcon(getClass().getResource("/images/projecticon.png"));
        setIconImage(i.getImage());
    }
    public static void setCurrentUser(String u)
    {
        currentUser=u;
    }
    public static String getCurrentUser()
    {
        return currentUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generateQuestion = new javax.swing.JLabel();
        updateQuestion = new javax.swing.JLabel();
        manageSubjects = new javax.swing.JLabel();
        manageUsers = new javax.swing.JLabel();
        updatePassword = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(220, 40, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        generateQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generate.png"))); // NOI18N
        generateQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generateQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateQuestionMouseClicked(evt);
            }
        });
        getContentPane().add(generateQuestion);
        generateQuestion.setBounds(40, 30, 200, 200);

        updateQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        updateQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateQuestionMouseClicked(evt);
            }
        });
        getContentPane().add(updateQuestion);
        updateQuestion.setBounds(280, 10, 210, 210);

        manageSubjects.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/subjects.png"))); // NOI18N
        manageSubjects.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageSubjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageSubjectsMouseClicked(evt);
            }
        });
        getContentPane().add(manageSubjects);
        manageSubjects.setBounds(550, 10, 200, 210);

        manageUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manageusers .png"))); // NOI18N
        manageUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageUsersMouseClicked(evt);
            }
        });
        getContentPane().add(manageUsers);
        manageUsers.setBounds(30, 290, 210, 180);

        updatePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updatepassword.png"))); // NOI18N
        updatePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatePasswordMouseClicked(evt);
            }
        });
        getContentPane().add(updatePassword);
        updatePassword.setBounds(290, 280, 210, 210);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(560, 270, 200, 210);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Manage Users");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 500, 140, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Generate Question");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 240, 140, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Update Question");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 230, 140, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Manage Subjects");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(590, 220, 140, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Logout");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(640, 490, 60, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Update Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(340, 500, 140, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background2.jpg"))); // NOI18N
        background.setMinimumSize(new java.awt.Dimension(1000, 1000));
        getContentPane().add(background);
        background.setBounds(-30, -100, 940, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateQuestionMouseClicked
        // TODO add your handling code here:
        admin.GenerateQuestion.main(new String[]{});
        dispose();
    }//GEN-LAST:event_generateQuestionMouseClicked

    private void updateQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateQuestionMouseClicked
        // TODO add your handling code here:
        UpdateQuestion.main(new String[]{});
        dispose();
    }//GEN-LAST:event_updateQuestionMouseClicked

    private void manageSubjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageSubjectsMouseClicked
        // TODO add your handling code here:
        managesubjects.ManageSubjects.main(new String[]{});
        dispose();
    }//GEN-LAST:event_manageSubjectsMouseClicked

    private void updatePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatePasswordMouseClicked
        // TODO add your handling code here:
        ChangePassword.main(new String[]{});
        dispose();
    }//GEN-LAST:event_updatePasswordMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        currentUser=null;
        questionsgenerator.QuestionsGenerator.main(new String[]{});
        dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void manageUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUsersMouseClicked
        // TODO add your handling code here:
        ManageUsers.main(new String[]{});
        dispose();
        
    }//GEN-LAST:event_manageUsersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel generateQuestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel manageSubjects;
    private javax.swing.JLabel manageUsers;
    private javax.swing.JLabel updatePassword;
    private javax.swing.JLabel updateQuestion;
    // End of variables declaration//GEN-END:variables
}
